AWSTemplateFormatVersion: '2010-09-09'
Description: S3

Parameters:
  NameBucket:
    Type: String
    Description: Nome do Bucket
    Default: optimize

Resources:
  S3BucketCode:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${NameBucket}-s3-code

Outputs:
  S3BucketName:
    Value: !Ref S3BucketCode
    Description: Nome do bucket
    Export:
      Name: S3BucketName
